use_frameworks!

platform :ios, '9.0'

target 'FPLogging_Example' do
  pod 'FPLogging', :path => '../'

  target 'FPLogging_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
